# Generated by Django 3.0.3 on 2020-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('contact_info', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('profile_photo', models.CharField(max_length=100)),
                ('joined_date', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
