# Generated by Django 3.0.3 on 2020-06-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('gold_weight', models.CharField(max_length=50)),
                ('silver_weight', models.CharField(max_length=50)),
                ('bronze_weight', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee.Employee', verbose_name='Tasks')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
