# Generated by Django 3.0.3 on 2020-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200629_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetasks',
            name='image',
            field=models.ImageField(blank=True, upload_to='tasks/images/'),
        ),
    ]
